postgresql_datadog_db_password: "{{ vault_postgresql_datadog_db_password }}"
postgresql_version: 11
postgresql_listen_addresses: "localhost"
postgresql_ufw_allow_network: 0.0.0.0/0
postgresql_lineinfiles:
  - { regexp: "listen_addresses = ", line: "listen_addresses = '{{ postgresql_listen_addresses }}'" }
